//
// Created by dhrum on 26-07-2026.
//

#ifndef RUBIKSCUBESOLVER_GENERICRUBIKSCUBESOLVER_H
#define RUBIKSCUBESOLVER_GENERICRUBIKSCUBESOLVER_H


class GenericRubiksCubeSolver {
};


#endif //RUBIKSCUBESOLVER_GENERICRUBIKSCUBESOLVER_H
